### ISSUE TITLE
I will try to not use Medium anymore

### ISSUE THREAD

**Issue by erickpatrick** [erickpatrick/erickpatrick.github.io#27]
```
---
 title: I will try to not use Medium anymore
 date: 2019-04-03T22:00:00.000Z
 description: How I'm trying to get Medium free as much as possible...
 categories:
   - miscellanea
 featured: false
 extends: _layouts.post
 section: content
 ---
 ```
